### ISSUE TITLE
running cal_precision.py and precision is 0.118

### ISSUE THREAD

**Issue by AlonAzrael** [js05212/MXNet-for-CDL#1]
Hi, I tried to do the expriment by running cdl.py first and then cal_precision.py, the precision I can get is 0.118, the cut off number is 8. 
Is this precision normal? or am I doing anything wrong?

Thanks advanced.

**Comment by js05212** [comment]
Hi, how many iterations did you train and how large did you set hyperparameters like K?

**Comment by AlonAzrael** [comment]
I use the default values, and just run python cdl.py.

**Comment by js05212** [comment]
Yes. Then I think it is normal. Note that as mentioned in the README, here 'we do not use pretrain and sigmoid activation (as used in the matlab/C++ code for CDL) in this version of code, which may harm the performance'.

**Comment by daicoolb** [comment]
Hi,After running " python cdl.py" I have this problem：
Traceback (most recent call last):
  File "cdl.py", line 61, in <module>
    lr_scheduler=mx.misc.FactorScheduler(20000,0.1))
  File "/home/daicoolb/MXNet-for-CDL/autoencoder.py", line 175, in finetune
    0, n_iter, {}, False)
  File "/home/daicoolb/MXNet-for-CDL/solver.py", line 84, in solve
    update_dict = {name: nd for name, nd in zip(sym.list_arguments(), exe.grad_a                                                                                        rrays) if nd}
  File "/home/daicoolb/MXNet-for-CDL/solver.py", line 84, in <dictcomp>
    update_dict = {name: nd for name, nd in zip(sym.list_arguments(), exe.grad_a                                                                                        rrays) if nd}
  File "/usr/local/lib/python2.7/dist-packages/mxnet/ndarray.py", line 238, in _                                                                                        _bool__
    raise ValueError("The truth value of an NDArray with more than one element i                                                                                        s ambiguous.")
ValueError: The truth value of an NDArray with more than one element is ambiguou                                                                                        s.
