### ISSUE TITLE
I am getting a syntax Error on Line 34 can someone please help ?

### ISSUE THREAD

**Issue by m2rik** [js05212/MXNet-for-CDL#5]

**Comment by js05212** [comment]
Which file? Could you post the error message?

**Comment by m2rik** [comment]
yes ,here is a snippet.
![error1](https://user-images.githubusercontent.com/26003054/31424432-ceb2cc3e-ae77-11e7-8d5f-a0358d0c8c8f.PNG)

**Comment by m2rik** [comment]
Okay ,solved the error it was just my version of python . but  a scalar error is coming up now
![error2](https://user-images.githubusercontent.com/26003054/31426349-9b5f5dc6-ae80-11e7-93b4-ba073e012ab8.PNG)
